name: rl4rs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.19.2
  - scipy=1.3.1
  - pandas=1.1.5
  - matplotlib
  - jupyter
  - notebook
  - ipykernel
  - scikit-learn=0.24.2
  - h5py=2.10.0
  - cython
  - pip
  - pip:
    - tensorflow==1.15.0
    - torch==1.9.0
    - gym==0.19.0
    - ray[default]==1.5.1
    - d3rlpy==0.91
    - deepctr==0.9.0
    - keras==2.2.5
    - keras-embed-sim==0.10.0
    - keras-layer-normalization==0.16.0
    - keras-multi-head==0.29.0
    - keras-pos-embd==0.13.0
    - keras-position-wise-feed-forward==0.8.0
    - keras-self-attention==0.51.0
    - keras-transformer==0.40.0
    - fairseq==0.10.2
    - lightseq==2.1.4
    - opencv-python-headless==4.3.0.36
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - blessings==1.7
    - click==8.0.1
    - cloudpickle==1.6.0
    - flask==1.1.2
    - hydra-core==1.1.1
    - joblib==1.0.1
    - lz4==3.1.3
    - msgpack==1.0.2
    - omegaconf==2.1.1
    - protobuf==3.19.3
    - psutil==5.8.0
    - pyyaml==5.4.1
    - redis==3.5.3
    - requests==2.27.1
    - structlog==21.3.0
    - tabulate==0.8.9
    - tensorboard==1.15.0
    - tensorboardx==2.4.1
    - tqdm==4.62.2
    - pandasql==0.7.3
    - gputil==1.4.0
